### ISSUE TITLE
Typo in project URL

### ISSUE THREAD

**Issue by wasamasa** [Sasanidas/lemmigton#1]
In case this is intended in the "Trolling is a art" sense, please just close this issue.

In case it's not, there is an inconsistency between the file being lemmington.el, lemmington- being the prefix, it being called Lemmington in the README, ... and it being lemmigton (note the missing n) in the URL and a few parts of the code. So for the sake of consistency, please choose only one of them. Thank you.

**Comment by Sasanidas** [comment]
It was indeed a typo :facepalm: , thanks for the issue, it should be solved now

**Comment by wasamasa** [comment]
Yup, looks good now.
