### ISSUE TITLE
i tried both use+package+/straight , latest emacs on nixos, it doesn't build

### ISSUE THREAD

**Issue by 0xameer** [Sasanidas/lemmigton#3]
![image](https://github.com/lem-project/lemmington/assets/847157/a733a26b-daca-447f-a393-d12250c9a566)

**Comment by Sasanidas** [comment]
Oh! Nice catch, I didn't had https://github.com/Wilfred/elisp-refs in the required packages. I update the file on master, let me know if it solved the issue :+1:

**Comment by Sasanidas** [comment]
I think with the change, the issue got solved so I'm going to close it. Feel free to open it again if that wasn't the case :+1:
